import Header from '@/components/Header'
import '../../styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Banner from '@/components/Banner'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: `Max's blog`,
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} max-w-7xl mx-auto`}>
        <Header />
        <Banner />
        {children}
      </body>
    </html>
  )
}
